### ISSUE TITLE
How does this compare to fd? 

### ISSUE THREAD

**Issue by krijoh92** [caengen/file-search#1]
https://github.com/sharkdp/fd

**Comment by caengen** [comment]
1. https://doma.dev/blog/parsing-stuff-in-rust/
TLDR: This uses nom, a parser combinator, not regex. Parsers are inherently faster than regex by an order of magnitude. 
2. Unlike regex this will be sensible and maintainable by humans. If you can read and maintain large regexes you fail my personal captcha.
